class EngineKeys:
    SNOWFLAKE_ACCOUNT = "vc83620.us-east4.gcp"
    SNOWFLAKE_USER = "SAHIL"
    SNOWFLAKE_PASSWORD = "Aa@123456"
    SNOWFLAKE_WAREHOUSE = "BINTI_WAREHOUSE"
    SNOWFLAKE_ROLE = "ACCOUNTADMIN"

